version: '3'

services:
  db:
    image: postgres
    volumes:
        - db_data:/var/lib/postgresql/data
    ports:
      - "5001:5001"
    command: -c port=5001
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: root
      POSTGRES_DB: participants

volumes:
  db_data:
